### ISSUE TITLE
pocket leaves bounds

### ISSUE THREAD

**Issue by tbfleming** [andrewhodel/millcrum#3] opened 2015-06-23 02:59 UTC
``` javascript
var tool = {units:'mm',diameter:6.35,passDepth:4,step:1,rapid:2000,plunge:100,cut:600,zClearance:5,returnHome:true};
var mc = new Millcrum(tool);
mc.surface(300,300);

var polygon = {type:'polygon',points:[
    [0,0],
    [100,0],
    [50,50],
    [100,100],
    [0,100],
]};

mc.cut('pocket', polygon, 6, [10,10]);
mc.get();
```

![image](https://cloud.githubusercontent.com/assets/418464/8298106/4db6ff1a-1932-11e5-8018-809777b295ec.png)

**Comment by andrewhodel** [comment] 2015-06-23 14:08
Interesting, here's what it does on FF which is still an error but a little different than Chrome.
I'll take a look into resolving that, it looks as simple as if (axis > maxAxis) { drop point } for Chrome and a bit more difficult for FF.

What's strange and what I'll have to figure out first is why or how the 2 different JS engines are generating the paths differently.

![ff_millcrum_pocket_error](https://cloud.githubusercontent.com/assets/741705/8307939/5f757b64-1987-11e5-865f-758d0a7a0bc6.png)

**Comment by andrewhodel** [comment] 2015-06-23 15:22
That commit fixes it to where pocket will remove the correct material for a shape like that.  It can be improved by creating multiple paths when a point in a path intersects another one then redrawing the next inside path of the pocket operation as N paths inside those newly created multiple paths.

Nonetheless, this works as intended for now and I can add that later.

![ss](https://cloud.githubusercontent.com/assets/741705/8309747/b927e30e-1991-11e5-88ea-e48f8952bdfc.png)

**Closed as completed by andrewhodel** 2015-06-23 15:22 UTC
